function navUI(){
	return '<div id="nav">'
+'    <section class="features-icons bg-light text-center">'
+'      <div class="container">'
+'        <div class="row">'
+'          <div class="col-lg-4" id="login_btn">'
+'            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">'
+'              <div class="features-icons-icon d-flex">'
+'                <i class="icon-screen-desktop m-auto text-primary"></i>'
+'   			  </div>'
+'            	   		<h3 id="login_label">로그인</h3>' 
+'              <p class="lead mb-0" id="login_text">로그인하여 <br>서비스를 이용하세요</p>'
+'            </div>'
+'          </div>'
+'          <div class="col-lg-4" id="join_btn">'
+'            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">'
+'              <div class="features-icons-icon d-flex">'
+'                <i class="icon-layers m-auto text-primary"></i>'
+'              </div>'
+'	              <h3 id="join_label"> 회원가입 </h3>'
+'              <p class="lead mb-0" id="join_text">보다 나은 서비스를 위하여<br>'
+'              						회원가입 하세요.</p>'
+'            </div>'
+'          </div>'
+' 			<div class="col-lg-4" id="board">'
+' 			<div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">'
+' 			  <div class="features-icons-icon d-flex">'
+' 			    <i class="icon-layers m-auto text-primary"></i>'
+' 			  </div>'
+' 			      <h3> 게시글 목록보기  </h3>'
+' 			  		<p class="lead mb-0"> 게시글 보러 가기 입니다.</p>'
+' 			</div>'
+' 			</div>'
+'          <div class="col-lg-4" id="admin_btn">'
+'            <div class="features-icons-item mx-auto mb-0 mb-lg-3">'
+'              <div class="features-icons-icon d-flex">'
+'                <i class="icon-check m-auto text-primary"></i>'
+'              </div>'
+'              <h3>관리자</h3>'
+'              <p class="lead mb-0" id="admin_btn">관리자 이용 메뉴입니다.</p>'
+'            </div>'
+'          </div>'
+'        </div>'
+'      </div>'
+'    </section>';
+'</div>';
}