<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<div id="content-box">
	<table>
			<tr>
				<td>아이디</td>
				<td>${user.userid}</td>
			</tr>
			<tr>
				<td>이메일</td>
				<td>${user.email}</td>
			</tr>
			<tr>
				<td>비밀번호</td>
				<td>********</td>
			</tr>
			<tr>
				<td>나이</td>
				<td>${user.age}</td>
			</tr>
			<tr>
				<td>팀아이디</td>
				<td>${user.teamid}</td>
			</tr>
			<tr>
				<td>성별</td>
				<td>${user.gender}</td>
			</tr>
			<tr>
				<td>역할</td>
				<td>${user.roll}</td>
			</tr>
			<tr>
				<td>연락처</td>
				<td>${user.phone}</td>
			</tr>
			<tr>
				<td>수강과목</td>
				<td>${user.subject}</td>
			</tr>
	</table>
</div>